### ISSUE TITLE
optional values in scala translates wrongly in `io-ts`

### ISSUE THREAD

**Issue by fes300** [buildo/metarpheus-io-ts#57]
## description
when a property is described as optional in a Scala model, it is translated into a runtime `io-ts` type that requires the property on the the type instance to be defined.

## how to reproduce
for instance this Scala code:
```
case class Budget(title: String,
                  value: Option[String],
                  notes: Option[String],
                  costs: List[Cost])
```

generates this runtime type:
```
const Budget = t.interface({
  title: t.string,
  value: t.union([
    t.string,
    t.undefined
  ]),
  notes: t.union([
    t.string,
    t.undefined
  ]),
  costs: t.array(Cost)
}, 'Budget')
```

which will throw a validation error whenever you define a Budget object without the `value` or `notes` prop (although it is a perfectly valid representation).

## specs
this problem would be solved by means of a mix of `intersection` and `partial` this way:
```
const Budget = t.intersection(
  [
   // Mandatory properties
    t.interface({
      title: t.string,
      costs: t.array(Cost),
    }),
   
   // Optional properties
    t.partial({
      value: t.union([t.string, t.undefined]),
      notes: t.union([t.string, t.undefined]),
      costs: t.array(Cost),
    }),
  ],
  'Budget',
);
```

**Comment by gabro** [comment]
Newer versions of io-ts-codegen seem to do this (to double check)
