### ISSUE TITLE
Decode Unit as void instead of empty object

### ISSUE THREAD

**Issue by ecamellini** [buildo/metarpheus-io-ts#77]
The Scala `Unit` type is currently translated as `{}`, but having it converted to `void` would be nicer in terms of TS types.

**Comment by gabro** [comment]
Caveat: wiro actually sends `{}` when the return type is `Unit`.

Using `void` at typelevel is a lie (an innocent one), but using `t.void` at runtime would be an error.

**Comment by ecamellini** [comment]
@gabro yep, what I mean here is to actually convert the values at runtime too: when seeing `{}`, return `undefined` or something like that. Otherwise, every time we want an `avenger` command to return `void`, we need to explicitly do `map(_ => undefined)`
